### ISSUE TITLE
I think that Frontpoint has disabled API access

### ISSUE THREAD

**Issue by ifeign** [jhurliman/homebridge-frontpoint#12]
```
Error: POST https://my.frontpointsecurity.com/api/Login/token failed: invalid json response body at https://my.frontpointsecurity.com/api/Login/token reason: Unexpected token T in JSON at position 0
    at /homebridge/node_modules/homebridge-frontpoint/node_modules/frontpoint/index.js:327:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

When visiting the url [https://my.frontpointsecurity.com/api/Login/token](https://my.frontpointsecurity.com/api/Login/token) I get 

> The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.

I suspect they are shutting this down, because yesterday I was forced to do a password reset due to "suspicious activity."

Oddly enough, this plugin worked an hour ago.

I'm not knowledgeable enough to actually verify this theory.

**Comment by ifeign** [comment]
Update: it appears that the Frontpoint website is undergoing maintenance. The URL now directs to  this message:

> Site Maintenance in Progress
> Hello, we're currently working to update our site for an improved customer experience in the future.
> 
> 
> While some content may be unavailable right now, you can still manage your system using the link below.

Will update/close this issue if resolved after maintenance.

**Comment by johncameron3** [comment]
Having similar issues.  I've had to reset my pw multiple times due to 'suspicious activity' as well.  After the reset, the next day I got a call asking me to reset my pw again.  Very odd.  I suspect they are having some major problems.

**Comment by jocamero** [comment]
Having similar issues. I've had to reset my pw multiple times due to 'suspicious activity' as well. After the reset, the next day I got a call asking me to reset my pw again. Very odd. I suspect they are having some major problems.

**Comment by ifeign** [comment]
Same thing happened to me. I’ve since switched to https://github.com/mkormendy/homebridge-node-alarm-dot-com and have no longer had issues, since it uses the alarm.com api and not the Frontpoint one. Everything seems to work fine.

**Comment by jhurliman** [comment]
It sounds like the set of endpoints this module was designed around have been retired. I don’t own this alarm system anymore, so I’m unable to test if any changes actually work or not. I’d be happy to transfer ownership of anyone thinks there is value in maintaining this node, otherwise will mark it as deprecated and link to node-alarm-dot-com

**Comment by jocamero** [comment]
Thanks for the updates guys.  I went ahead and migrated to the suggested node-alarm-dot-com and everything is working again.  @jhurliman , thanks for your previous work on the FrontPoint project.

**Comment by jocamero** [comment]
I'm still not clear if anything has been retired or if things on their end are still just broken.  If you goto https://my.frontpointsecurity.com/login it has said 'site maintenance in progress' for many days. Once they fix things on their end, I suspect this node might start working again?

**Comment by ifeign** [comment]
I spoke to support, they’re doing site maintenance, it’s not just a generic
error. It’s possible things will work again once they’re done.
